#define G2s 425
#define G2 450
#define A2s 378
#define F2 505
#define A1 802

#define BMAN_PULSE1_00 \
{G2, HALF, SQR_WAVE}, \
{G2s, QUART, SQR_WAVE}, \
{A2s, EIGHT, SQR_WAVE}, \
{G2, WHOLE, SQR_WAVE}, \
{REST, EIGHT, SQR_WAVE}, \
{F2, HALF, SQR_WAVE}, \
{F2, QUART, SQR_WAVE}, \
{G2, EIGHT, SQR_WAVE}, \
{A1, EIGHT, SQR_WAVE}, \
{G4, EIGHT, SQR_WAVE}, \
{G4, EIGHT, SQR_WAVE}, \
{C4s, QUART, SQR_WAVE}, \
{G4, EIGHT, SQR_WAVE}, \
{G4, EIGHT, SQR_WAVE}, \
{C4s, QUART, SQR_WAVE}

sample_t bubbleman = {

BMAN_PULSE1_00,
BMAN_PULSE1_00

}
